ohorbatiuk/d8

composer.json

Update core from 5.3 to 5.4

---

composer.json

Updated "Admin Toolbar" module from 1.23 to 1.24

---

composer.json

Update core from 5.4 to 5.5

---

composer.json

Update core from 5.5 to 5.6

---

composer.json

Update "Bootstrap" theme from 3.11 to 3.12

---

composer.json

Update core from 5.6 to 6.0

---

composer.json

Update core from 6.0 to 6.1

---

composer.json

Update core from 6.1 to 6.2

---

composer.json

Update core from 6.2 to 6.3

---

composer.json

Update "Admin Toolbar" module from 1.24 to 1.25

---

composer.json

Update core from 6.3 to 6.4

---

composer.json

Update "Features" module from 3.7 to 3.8

---

composer.json

Update "Bootstrap" theme from 3.15 to 3.16

---

composer.json

39: Update core from 6.4 to 6.7

---

composer.json

40: Update "Configuration Update Manager" module from 1.5 to 1.6

---

composer.json

41: Update "Bootstrap" theme from 3.16 to 3.17

---

composer.json
modules/features/d8_captcha/config/install/recaptcha.settings.yml
src/Captcha.php
themes/custom/d8_theme/src/Plugin/Process/Captcha.php

45: Update "reCAPTCHA" module from 2.3 to 2.4

---

composer.json

47: Update core from 6.7 to 6.10

---

composer.json

48: Update "Admin Toolbar" module from 1.25 to 1.26

---

composer.json

53: Update core from 6.10 to 6.12

---

composer.json

55: Update core from 6.12 to 6.13

---

composer.json
d8.info.yml
d8.install

58: Install "Config Export to PHP array" module

---

composer.json

56: Update "Automatic IP ban (Autoban)" module from 1.2 to 1.4

---

composer.json

60: Update "Config Export To PHP Array" module from 1.0-alpha1 to 1.0-alpha2

---

composer.json

61: Update core from 6.13 to 6.15

---

composer.json

65: Update core from 6.15 to 6.16

---

composer.json

66: Update "Bootstrap" theme from 3.17 to 3.19

---

composer.json
d8.info.yml
d8.install
modules/custom/recaptcha_preloader/recaptcha_preloader.routing.yml
modules/custom/recaptcha_preloader/src/Form/RecaptchaPreloaderSettingsForm.php
modules/features/d8_feature_blocks_d8_theme/config/install/block.block.d8_theme_account_menu.yml
modules/features/d8_feature_blocks_d8_theme/config/install/block.block.d8_theme_footer.yml
modules/features/d8_feature_blocks_d8_theme/config/install/block.block.d8_theme_main_menu.yml
modules/features/d8_feature_blocks_d8_theme/config/install/block.block.d8_theme_tools.yml
modules/features/d8_feature_blocks_seven/config/install/block.block.seven_admin.yml
modules/features/d8_feature_blocks_seven/config/install/block.block.seven_tools.yml
modules/features/d8_feature_settings/d8_feature_settings.install
src/Form/D8CaptchaForm.php

69: Update core from 6.16 to 7.1

---

composer.json
d8.profile
modules/custom/recaptcha_preloader/src/Controller/DisableRecaptchaNoscript.php
modules/custom/recaptcha_preloader/src/Form/RecaptchaPreloaderSettingsForm.php
src/Form/D8CaptchaForm.php

71: Update core from 7.1 to 7.6

---

composer.json

72: Update "Bootstrap" theme from 3.19 to 3.20

---

composer.json
modules/features/d8_ban/config/install/autoban.autoban.open_absent_page_by_anonymous.yml

76: Update "Automatic IP ban (Autoban)" module from 1.4 to 1.5

---

composer.json

78: Update core from 7.6 to 7.7

---

composer.json

73: Update "Admin Toolbar" module from 1.26 to 1.27

---

composer.json

87: Update "CAPTCHA" module from 1.0-beta3 to 1.0-beta4

---

composer.json

89: Update "Admin Toolbar" module from 1.27 to 2.0

---

composer.json

91: Update core from 7.8 to 8.0

---

composer.json

97: Entity events

---

composer.json

95: Update core from 8.0 to 8.3

---

composer.json

104: Update core from 8.4 to 8.5

---

composer.json

93: Update "Config Export to PHP array" module from 1.0-alpha2 to 2.0.0-beta2

---

composer.json

107: Update "Admin Toolbar" module from 2.0 to 2.2

---

composer.json

100: Update "CAPTCHA" module from 1.0-beta4 to 1.0

---

composer.json

96: Update "Automatic IP ban (Autoban)" module from 1.5 to 1.6

---

composer.json

112: Update "Configuration Update Manager" module from 1.6 to 1.7

---

composer.json

92: Update "Bootstrap" theme from 3.20 to 3.21

---

composer.json

120: Update core from 8.5 to 8.6

---

composer.json

124: Update core from 8.6 to 9.0

---

composer.json

127: Update core from 9.0 to 9.1

---

composer.json

131: Update core from 9.1 to 9.6

---

composer.json

133: Update core from 9.6 to 9.9

---

composer.json

135: Update core from 9.9 to 9.10

---

composer.json

137: Update core from 9.10 to 9.13

---

composer.json
d8.info.yml

125: Update "Bootstrap" theme from 3.21 to 3.23

---

composer.json
d8.info.yml

119: Update "Config Export to PHP array" module from 2.0.0-beta2 to 2.0.0

---

d8.info.yml
d8.install
modules/custom/d8_config2php/d8_config2php.info.yml
modules/custom/d8_config2php/d8_config2php.module

145: Change default page for exporting configuration

---

composer.json
d8.info.yml

148: Composer 2

---

composer.json
d8.info.yml

150: Update "Admin Toolbar" module from 3.0.0 to 3.0.2

---

composer.json
d8.info.yml
d8.install

157: News mode

---

composer.json
d8.info.yml
modules/features/d8_captcha/config/install/captcha.settings.yml

122: Update "CAPTCHA" module from 1.0 to 1.2

---

composer.json
d8.info.yml

156: Update "reCAPTCHA" module from 2.5 to 3.0

---

composer.json
d8.info.yml

151: Update "Config override" module from 1.0-beta2 to 1.0-rc1

---

composer.json
d8.info.yml

140: Update "Module Filter" module from 3.1 to 3.2

---

composer.json
d8.info.yml
d8.install

171: Install "StandWithUkraine" module

---

README.md
composer.json
d8.info.yml

174: Update "StandWithUkraine" module from 1.0.0 to 1.0.1

---

composer.json
d8.info.yml

177: Update "Bootstrap" module from 3.23 to 3.24

---

composer.json
d8.info.yml

176: Update "StandWithUkraine" module from 1.0.1 to 1.0.2

---

composer.json
d8.info.yml
d8.install
modules/features/d8_standwithukraine/config/install/standwithukraine.settings.yml
modules/features/d8_standwithukraine/d8_standwithukraine.features.yml
modules/features/d8_standwithukraine/d8_standwithukraine.info.yml
modules/features/d8_standwithukraine/d8_standwithukraine.install
modules/features/d8_standwithukraine/d8_standwithukraine.module

181: Update "StandWithUkraine" module from 1.0.2 to 1.1.0

---

composer.json
d8.info.yml
modules/features/d8_standwithukraine/config/install/standwithukraine.settings.yml
modules/features/d8_standwithukraine/d8_standwithukraine.module

Update "StandWithUkraine" module from 1.1.0 to 1.2.0

---

composer.json
d8.info.yml
modules/features/d8_standwithukraine/d8_standwithukraine.module

Update "StandWithUkraine" module from 1.2.0 to 1.2.1

---

README.md
composer.json
d8.info.yml
modules/features/d8_standwithukraine/config/install/standwithukraine.settings.yml
modules/features/d8_standwithukraine/d8_standwithukraine.info.yml

Update "StandWithUkraine" module from 1.2.1 to 1.3.3

---

composer.json
d8.info.yml

Update "Admin Toolbar" module from 3.0.2 to 3.1.1

---

composer.json
d8.info.yml
modules/features/d8_standwithukraine/config/install/standwithukraine.settings.yml
modules/features/d8_standwithukraine/d8_standwithukraine.module

Update "StandWithUkraine 🇺🇦" module from 1.3.3 to 1.3.4

---

composer.json
d8.info.yml
modules/features/d8_ban/config/install/autoban.autoban.open_absent_page_by_anonymous.yml

Update "Automatic IP ban (Autoban)" module from 1.6 to 1.7

---

README.md
composer.json
d8.info.yml
d8.install

Install "Upgrade Status" module

---

composer.json
d8.info.yml
modules/features/d8_captcha/config/install/captcha.captcha_point.user_login_form.yml

Update "CAPTCHA" module from 1.2 to 1.5

---

composer.json
d8.info.yml
d8.install
modules/features/d8_standwithukraine/config/install/standwithukraine.settings.yml
modules/features/d8_standwithukraine/d8_standwithukraine.info.yml
modules/features/d8_standwithukraine/src/D8StandWithUkraineNegotiator.php

Update "StandWithUkraine 🇺🇦" module from 1.3.6 to 1.3.7

---

composer.json
d8.info.yml

Update "Admin Toolbar" module from 3.1.1 to 3.3.0

---

composer.json
d8.info.yml
modules/features/d8_captcha/d8_captcha.info.yml
src/Form/D8CaptchaForm.php

Update "reCAPTCHA" module from 3.0 to 3.1

---

composer.json
d8.info.yml
modules/features/d8_feature_blocks_d8_theme/config/install/block.block.d8_theme_branding.yml
modules/features/d8_feature_blocks_d8_theme/d8_feature_blocks_d8_theme.info.yml
modules/features/d8_feature_blocks_seven/config/install/block.block.seven_branding.yml
modules/features/d8_feature_blocks_seven/d8_feature_blocks_seven.info.yml

Update "StandWithUkraine 🇺🇦" module from 1.3.7 to 1.3.8

---

composer.json
d8.info.yml
modules/features/d8_feature_blocks_d8_theme/config/install/block.block.d8_theme_branding.yml

Update "StandWithUkraine 🇺🇦" module from 1.3.8 to 1.3.9

---

composer.json
d8.info.yml
modules/features/d8_config2php/d8_config2php.info.yml

Update "Config Export to PHP array" module from 2.0.1 to 2.0.2

---

README.md
composer.json
d8.info.yml

Delete "Config override" module

---

README.md
composer.json
d8.info.yml

Update "Module Filter" module from 3.2 to 4.0.1

---

composer.json
d8.info.yml
d8.install

Update "Features" module from 3.12 to 3.13

---

composer.json
d8.info.yml

Update "Admin Toolbar" module from 3.3.0 to 3.4.1

---

composer.json
d8.info.yml

Update "Upgrade Status" module from 3.17 to 3.19

---

d8.info.yml
d8.install

Uninstall "Upgrade Status" module

---

README.md
composer.json
d8.info.yml

Delete "Upgrade Status" module

---

composer.json
d8.info.yml
modules/features/d8_config2php/config/install/config2php.settings.yml
modules/features/d8_config2php/d8_config2php.info.yml

Update "Config Export to PHP array" module from 2.0.2 to 2.1.0

---

composer.json
d8.info.yml

Update "StandWithUkraine 🇺🇦" module from 1.3.9 to 1.3.10

---

.github/ISSUE_TEMPLATE/update-module.md
.github/ISSUE_TEMPLATE/update-theme.md
composer.json
d8.info.yml
themes/custom/d8_theme/src/Plugin/Alter/ThemeSuggestions.php

Update "Bootstrap" theme from 3.28 to 3.29

---

composer.json
d8.info.yml
modules/features/d8_mail/d8_mail.module

Update "Drupal Symfony Mailer" module from 1.2.2 to 1.3.2

---

composer.json
d8.info.yml
modules/features/d8_captcha/config/install/recaptcha.settings.yml
modules/features/d8_captcha/d8_captcha.install

Update "reCAPTCHA" module from 3.1 to 3.2

---

composer.json
d8.info.yml
modules/features/d8_captcha/d8_captcha.info.yml
modules/features/d8_captcha/d8_captcha.module
src/Form/D8CaptchaForm.php

Update "reCAPTCHA Preloader" module from 1.0.1 to 2.0.0

---

composer.json
d8.info.yml
modules/features/d8_captcha/config/install/captcha.settings.yml
modules/features/d8_captcha/d8_captcha.install
modules/features/d8_captcha/d8_captcha.module

Update "CAPTCHA" module from 1.9 to 2.0.5

---

README.md
composer.json
d8.info.yml
d8.install
modules/features/d8_log/src/Plugin/EmailAdjuster/LogEmailAdjuster.php
modules/features/d8_standwithukraine/src/D8StandWithUkraineNegotiator.php
src/Controller/D8MaintenanceController.php
src/Controller/D8WelcomeController.php
src/Form/D8CaptchaForm.php
src/Form/D8ConfigureForm.php
src/Service/D8ControllerResolver.php
themes/custom/d8_theme/src/Plugin/Alter/ThemeSuggestions.php

Install "Service" module

---

composer.json
d8.info.yml
modules/features/d8_standwithukraine/src/D8StandWithUkraineNegotiator.php

Update "StandWithUkraine 🇺🇦" module from 1.3.10 to 2.0.0

---

composer.json
d8.info.yml
modules/features/d8_config2php/d8_config2php.info.yml

Update "Config Export to PHP array" module from 2.1.0 to 3.0.0

---

composer.json
d8.info.yml

Update "Module Filter" module from 4.0.1 to 4.1.1

---

.github/ISSUE_TEMPLATE/update-core.md
.github/ISSUE_TEMPLATE/update-module.md
.github/ISSUE_TEMPLATE/update-theme.md
composer.json
d8.info.yml
d8.install
modules/features/d8_feature_blocks_d8_theme/d8_feature_blocks_d8_theme.info.yml
modules/features/d8_feature_blocks_seven/d8_feature_blocks_seven.info.yml
modules/features/d8_feature_menus/d8_feature_menus.info.yml
modules/features/d8_feature_settings/d8_feature_settings.info.yml
modules/features/d8_menu/d8_menu.features.yml
modules/features/d8_menu/d8_menu.info.yml
modules/features/d8_setting/d8_setting.features.yml
modules/features/d8_setting/d8_setting.info.yml
modules/features/d8_seven/d8_seven.features.yml
modules/features/d8_seven/d8_seven.info.yml
modules/features/d8_theming/d8_theming.features.yml
modules/features/d8_theming/d8_theming.info.yml

Update "Features" module from 3.13 to 3.14

---

composer.json
d8.info.yml
modules/features/d8_mail/d8_mail.info.yml
modules/features/d8_mail/d8_mail.module
modules/features/d8_mail/src/D8MailBuilder.php
src/D8BuilderBase.php
src/D8Setup.php

Update "Service" module from 1.0.0 to 2.0.0

---

.github/ISSUE_TEMPLATE/update-module-classic.md
.github/ISSUE_TEMPLATE/update-module-modern.md
composer.json
d8.info.yml
d8.install
modules/features/d8_config2php/d8_config2php.info.yml

Update "Config Export to PHP array" module from 3.0.0 to 3.0.2

---

composer.json
d8.info.yml
d8.install
modules/features/d8_captcha/d8_captcha.install
modules/features/d8_feature_blocks_d8_theme/d8_feature_blocks_d8_theme.features.yml
modules/features/d8_feature_blocks_d8_theme/d8_feature_blocks_d8_theme.info.yml
modules/features/d8_feature_blocks_seven/d8_feature_blocks_seven.features.yml
modules/features/d8_feature_blocks_seven/d8_feature_blocks_seven.info.yml
modules/features/d8_feature_menus/d8_feature_menus.features.yml
modules/features/d8_feature_menus/d8_feature_menus.info.yml
modules/features/d8_feature_settings/d8_feature_settings.features.yml
modules/features/d8_feature_settings/d8_feature_settings.info.yml
src/D8Setup.php

Update "reCAPTCHA Preloader" module from 2.0.0 to 2.0.1

---

composer.json
d8.info.yml

Update "reCAPTCHA" module from 3.2 to 3.3

---

README.md
composer.json
d8.info.yml
modules/features/d8_captcha/d8_captcha.info.yml

Update "CAPTCHA" module from 2.0.5 to 2.0.6

---

composer.json
d8.info.yml

Update "Module Filter" module from 4.1.1 to 5.0.3

---

composer.json
d8.info.yml
modules/features/d8_standwithukraine/config/install/standwithukraine.settings.yml
modules/features/d8_standwithukraine/src/D8StandWithUkraineNegotiator.php

Update "StandWithUkraine 🇺🇦" module from 2.0.0 to 2.0.2

---

composer.json
d8.info.yml
modules/features/d8_ban/d8_ban.info.yml

Update "Automatic IP ban (Autoban)" module from 1.9 to 1.10

---

.github/ISSUE_TEMPLATE/update-module-upgrade.md
composer.json
d8.info.yml
modules/features/d8_link/config/install/extlink.settings.yml
modules/features/d8_link/config/schema/d8_link.schema.yml
modules/features/d8_link/d8_link.info.yml
modules/features/d8_link/src/D8Url.php
modules/features/d8_link/src/Plugin/Field/FieldFormatter/D8LinkFormatter.php

Update "External Links" module from 1.7 to 2.0.2

---

.github/ISSUE_TEMPLATE/update-core.md
.github/ISSUE_TEMPLATE/update-module-classic.md
.github/ISSUE_TEMPLATE/update-module-modern.md
.github/ISSUE_TEMPLATE/update-module-upgrade.md
.github/ISSUE_TEMPLATE/update-theme.md
composer.json
d8.info.yml

Update "Configuration Update Manager" module from 2.0.0-alpha3 to 2.0.0-alpha4

---

composer.json
d8.info.yml

Update "Drupal Symfony Mailer" module from 1.3.2 to 1.4.1

---

composer.json
d8.info.yml
modules/features/d8_theming/d8_theming.install
src/D8Setup.php
themes/custom/d8_theme/config/install/d8_theme.settings.yml

Update "Bootstrap" theme from 3.29 to 3.32

---

.github/ISSUE_TEMPLATE/install-module.md
.github/ISSUE_TEMPLATE/update-core.md
.github/ISSUE_TEMPLATE/update-module-classic.md
.github/ISSUE_TEMPLATE/update-module-modern.md
.github/ISSUE_TEMPLATE/update-module-upgrade.md
.github/ISSUE_TEMPLATE/update-theme.md
composer.json
d8.info.yml

Update "Admin Toolbar" module from 3.4.1 to 3.5.0

---

composer.json
d8.info.yml

Update "Service" module from 2.0.0 to 2.0.1

---

.github/ISSUE_TEMPLATE/update-core.md
.github/ISSUE_TEMPLATE/update-module-classic.md
.github/ISSUE_TEMPLATE/update-module-modern.md
.github/ISSUE_TEMPLATE/update-module-upgrade.md
.github/ISSUE_TEMPLATE/update-theme.md
composer.json
d8.info.yml

Update "StandWithUkraine 🇺🇦" module from 2.0.2 to 2.0.3

---

composer.json
d8.info.yml
d8.install
d8.profile
modules/features/d8_mail/d8_mail.module
modules/features/d8_standwithukraine/d8_standwithukraine.info.yml

Update "StandWithUkraine 🇺🇦" module from 2.0.2 to 3.0.0

---

composer.json
d8.info.yml
modules/features/d8_theming/d8_theming.info.yml
themes/custom/d8_theme/d8_theme.info.yml

Bootstrap 3.32 to 3.34

---

README.md
composer.json
d8.info.yml

Features 3.14 to 3.14.3447460

---

composer.json
d8.info.yml

Font Awesome Icons 2.26 to 3.0.0

---

composer.json
d8.info.yml

Error & Exception Mailer 4.0.6 to 4.0.7

---

composer.json
d8.info.yml
modules/features/d8_theming/d8_theming.install

Idle 1.0.0 to 1.0.2

---

composer.json
d8.info.yml

reCAPTCHA Preloader 2.0.1 to 2.0.2

---

composer.json
d8.info.yml

Service 3.0.0 to 3.0.1

---

composer.json
d8.info.yml

Config Export to PHP array 3.0.2 to 3.0.3

---

composer.json
d8.info.yml

StandWithUkraine 🇺🇦 3.0.0 to 3.0.1

---

composer.json
d8.info.yml

Admin Toolbar 3.5.0 to 3.6.2

---

composer.json
d8.info.yml
modules/features/d8_link/config/install/extlink.settings.yml
modules/features/d8_link/d8_link.info.yml

External Links 2.0.2 to 2.0.5
